server:
  port: ${CONFIG_PORT:8761}
spring:
  application:
    name: registry-service

info:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false